# Generated by Django 4.2.6 on 2024-01-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_category_subscribers_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
